export const MESSAGE = {
    unauthorized: "unauthorized",
    invalidtoken: "invalid token",
    internalServerError: "internal Server Error",
    success: "success",
    Invalid_Role: "Invalid Role",
    tokenMissing: "authorization header missing or invalid",
    fetch_products: "An error occurred while fetching products.",
    fetch_orders: "An error occurred while fetching orders.",
    Unable_To_fetch_users: "An error occurred while fetching users.",
    Unable_To_fetch_items: "An error occurred while fetching items.",
    Unable_To_Update_users: "An error occurred while updating users.",
    Unable_To_Update_Items: "An error occurred while updating items.",
    Unable_To_Fetch_Orders: "An error occurred while fetching orders.",
    Unable_To_Delete_Orders: "An error occurred while deleting orders.",
    Unable_To_Delete_Products: "An error occurred while deleting products.",
    Unable_To_Create_Order: "An error occurred while create order.",
    Unable_To_Update_Order: "An error occurred while updating order.",
    Not_Found: "Not Found",
    false: false,
    true: true,
    Successfully_deleted: "Order deleted successfully",
    Product_deleted: "Product deleted successfully",
    User_Already_Exists: "User_Already_Exists",
    Invalid_email: "Invalid email",
    Invalid_password: "Invalid  password",
    BadRequest: "BadRequest",
    exists: "already_Exits",
    No_file_uploaded: "No_file_uploaded",
    Insufficient_Quantity: "Insufficient_Quantity",
    RequiredFields: "Product_id and Product_Quantity are required",
    Mail_Sent_Successfully: "MailSentSuccessfully",
    noFile: "noFile"
  };